# example config file please see data/sample_data/README.md
datasets:
  default: /home/ludmila/datasets/
  cifar10: /home/ludmila/datasets/
  cifar10_1: /home/ludmila/datasets/
  camelyon17: path/for/install
  camelyon_quantized: /home/ludmila/datasets/